//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SimplyAUTMotionController.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SIMPLYAUT_MOTIONCONTROLLER_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_CONNECT              129
#define IDD_DIALOG_MOTORS               130
#define IDD_DIALOG_GIRTHWELD            131
#define IDB_BITMAP_DISCONNECT           132
#define IDD_DIALOG_STATUS               132
#define IDB_BITMAP_CONNECT              133
#define IDD_DIALOG_STATUS1              133
#define IDD_DIALOG_LASER                133
#define IDB_BITMAP_PAUSE                134
#define IDD_DIALOG_MAG                  134
#define IDR_MENU1                       134
#define IDB_BITMAP_GO_HORZ              135
#define IDB_BITMAP_GO_RIGHT             135
#define IDD_DIALOG_FILES                135
#define IDB_BITMAP_GO_VERT              136
#define IDB_BITMAP_GO_DOWN              136
#define IDD_DIALOG_NAVIGATION           136
#define IDB_BITMAP_STOP                 137
#define IDD_DIALOG_NEW_FILE             137
#define IDB_BITMAP_LASER_OK             138
#define IDB_BITMAP_LASER_LOADING        139
#define IDB_BITMAP_LASER_HOT            140
#define IDB_BITMAP_LASER_ERROR          141
#define IDB_BITMAP_LASER_OFF            142
#define IDB_BITMAP_GO_LEFT              143
#define IDB_BITMAP_GO_UP                144
#define IDC_BUTTON_CONNECT              1001
#define IDC_IPADDRESS_LASER             1004
#define IDC_IPADDRESS_GALIL             1005
#define IDC_BUTTON_LASER                1006
#define IDC_BUTTON_RGB                  1007
#define IDC_BUTTON_MAG                  1008
#define IDC_BUTTON_GALIL                1009
#define IDC_STATIC_LASER                1010
#define IDC_STATIC_RGB                  1011
#define IDC_STATIC_MAG                  1011
#define IDC_STATIC_GALIL                1012
#define IDC_STATIC_LASER_IP             1013
#define IDC_IPADDRESS_MAG               1014
#define IDC_TAB1                        1015
#define IDC_STATIC_LASER_IP2            1015
#define IDC_EDIT_MA                     1016
#define IDC_STATIC_LASER_IP3            1016
#define IDC_EDIT_MB                     1017
#define IDC_STATIC_GALIL2               1017
#define IDC_EDIT_MC                     1018
#define IDC_EDIT_MD                     1019
#define IDC_STATIC_MA                   1020
#define IDC_STATIC_MB                   1021
#define IDC_STATIC_MC                   1022
#define IDC_STATIC_MD                   1023
#define IDC_STATIC_SPEED                1024
#define IDC_STATIC_MA2                  1024
#define IDC_STATIC_LR_OFFSET            1025
#define IDC_STATIC_MB2                  1025
#define IDC_EDIT_SPEED                  1026
#define IDC_STATIC_MC2                  1026
#define IDC_SPIN_SPEED                  1027
#define IDC_STATIC_MD2                  1027
#define IDC_EDIT_LR_OFFSET              1028
#define IDC_STATIC_SPEED2               1028
#define IDC_SPIN_LR_OFFSET              1029
#define IDC_EDIT_ACCEL                  1029
#define IDC_BUTTON_PAUSE                1030
#define IDC_SPIN_ACCEL                  1030
#define IDC_BUTTON_CALIB                1031
#define IDC_STATIC_SPEED3               1031
#define IDC_BUTTON_MANUAL               1032
#define IDC_BUTTON_AUTO                 1033
#define IDC_EDIT_ACCEL2                 1033
#define IDC_BUTTON_BACK                 1034
#define IDC_BUTTON_FWD                  1035
#define IDC_BUTTON_RIGHT                1036
#define IDC_SPIN_SEEK_START             1036
#define IDC_EDIT_CIRC                   1037
#define IDC_SPIN_CIRC                   1038
#define IDC_BUTTON_ZERO_HOME            1039
#define IDC_BUTTON_GO_HOME              1040
#define IDC_STATIC_PAUSE                1041
#define IDC_EDIT_STATUS                 1042
#define IDC_EDIT_DIST                   1042
#define IDC_RADIO_CIRC                  1043
#define IDC_RADIO_DIST                  1044
#define IDC_SPIN_DIST                   1045
#define IDC_CHECK_AUTOHOME              1046
#define IDC_EDIT_OVERLAP                1047
#define IDC_STATIC_HOMEDIST             1048
#define IDC_SPIN_OVERLAP                1049
#define IDC_STATIC_SCANNEDDIST          1050
#define IDC_CHECK_RETURNTOSTART         1051
#define IDC_STATIC_JOINT_LOCN           1052
#define IDC_STATIC_LASER_US             1053
#define IDC_STATIC_LASER_EDGE           1053
#define IDC_STATIC_LASER_DS             1054
#define IDC_STATIC_LASER_DIFF           1055
#define IDC_BUTTON_LASER_STATUS         1056
#define IDC_STATIC_MOTOR_A              1057
#define IDC_BUTTON_LEFT                 1057
#define IDC_CHECK_PREDRIVE              1057
#define IDC_STATIC_MOTOR_B              1058
#define IDC_CHECK_SEEK_START_REVERSE    1058
#define IDC_STATIC_MOTOR_C              1059
#define IDC_STATIC_TEMP_BOARD           1059
#define IDC_STATIC_MOTOR_A4             1060
#define IDC_STATIC_MOTOR_D              1060
#define IDC_STATIC_TEMP_LASER           1060
#define IDC_CHECK_MAG_ENGAGED           1061
#define IDC_STATIC_TEMP_SENSOR          1061
#define IDC_STATIC_MOTOR_A2             1061
#define IDC_INITIALISE_BUTTON           1062
#define IDC_STATIC_RUN_TIME             1062
#define IDC_STATIC_MOTOR_B2             1062
#define IDC_SERIALNUMBER_EDIT           1063
#define IDC_CHECK_SEEK_WITH_LASER       1063
#define IDC_STATIC_MOTOR_C2             1063
#define IDC_LASER_BUTTON                1064
#define IDC_SPIN_ACCEL2                 1064
#define IDC_STATIC_MOTOR_D2             1064
#define IDC_TEMPERATURE_EDIT            1065
#define IDC_SPIN_PREDRIVE               1065
#define IDC_MSG_EDIT                    1066
#define IDC_CHECK_SEEK_BLACK_LINE       1066
#define IDC_LASERPOWER_BUTTON           1067
#define IDC_STATIC_RGB_LINE             1067
#define IDC_CHECK_CALIBRATE             1067
#define IDC_LASERPOWER_EDIT             1068
#define IDC_STATIC_RGB_VALUE            1068
#define IDC_SENSORVERSION_EDIT          1069
#define IDC_STATIC_RGB_CALIBRATION      1069
#define IDC_CALIBRATIONVERSION_EDIT     1070
#define IDC_CHECK_SEEK_START_LINE       1070
#define IDC_AUTOLASER_CHECK             1071
#define IDC_PROFILECOUNT_EDIT           1072
#define IDC_LASERPOWER_SLIDER           1073
#define IDC_SHUTTER_SLIDER              1074
#define IDC_SHUTTER_EDIT                1075
#define IDC_JOINTPOS_EDIT               1076
#define IDC_EDGESPOS_EDIT               1077
#define IDC_GAPVALUE_EDIT               1078
#define IDC_MISMATCHVALUE_EDIT          1079
#define IDC_ROI_BUTTON                  1080
#define IDC_ROI_EDIT                    1081
#define IDC_CLOSE_BUTTON                1082
#define IDC_STATIC_PROFILE              1083
#define IDC_EDIT_MAG_PORT               1084
#define IDC_STATIC_MAG_VERSION          1085
#define IDC_STATIC_MAG_ENCODER          1086
#define IDC_CHECK_MAG_ENABLE            1087
#define IDC_BUTTON_MAG_CLEAR            1088
#define IDC_STATIC_MAG_ENCODER2         1089
#define IDC_STATIC_MAG_RGB              1089
#define IDC_BUTTON_MAG_ON               1090
#define IDC_BUTTON_ROI_RESET            1091
#define IDC_STATIC_RGB_STATUS           1091
#define IDC_BUTTON_MAG_ON2              1091
#define IDC_BUTTON_MAG_ERNABLED         1091
#define IDC_EDIT_RGB_CAL                1092
#define IDC_BUTTON_SET_CALIBRATION      1093
#define IDC_STATIC_MAG_RGB_CAL          1094
#define IDC_STATIC_MAG_RGB_LINE         1095
#define IDC_STATIC_LEFT                 1096
#define IDC_STATIC_RIGHT                1097
#define IDC_BUTTON_RESET_STATUS         1098
#define IDC_STATIC_WELD_OFFSET          1099
#define IDC_STATIC_WELD_WIDTH           1100
#define IDC_STATIC_WELD_LR_DIFF         1101
#define IDC_STATIC_WELD_HEIGHT          1102
#define IDC_CHECK_SHIFT_TO_CENTRE       1103
#define IDC_CHECK_SHOW_RAW_DATA         1104
#define IDC_BUTTON_RGB_CALIBRATION      1104
#define IDC_EDIT_RGB_CALIBRATION        1105
#define IDC_EDIT_RGB_SPEED              1106
#define IDC_CHECK_USE_LASER             1108
#define IDC_CHECK_RETURN_TO_START       1109
#define IDC_EDIT1                       1109
#define IDC_EDIT_SEEK_START_LINE        1109
#define IDC_EDIT_PROJECT                1109
#define IDC_STATIC_FWD                  1110
#define IDC_CHECK_USE_BLACK_LINE        1110
#define IDC_STATIC_BACK                 1111
#define IDC_STATIC1                     1112
#define IDC_STATICPID_P                 1112
#define IDC_STATIC2                     1113
#define IDC_STATICPID_I                 1113
#define IDC_STATIC3                     1114
#define IDC_STATICPID_D                 1114
#define IDC_STATIC4                     1115
#define IDC_STATICPID                   1115
#define IDC_SLIDER_STEER                1116
#define IDC_STATICPID_P2                1116
#define IDC_EDIT_PREDRIVE               1117
#define IDC_LIST1                       1117
#define IDC_LIST_FILES                  1117
#define IDC_STATICPID_P3                1117
#define IDC_BUTTON_RESET                1118
#define IDC_STATIC_MAG_STATUS           1118
#define IDC_EDIT_NAV_P                  1119
#define IDC_EDIT_NAV_I                  1120
#define IDC_EDIT_NAV_D                  1121
#define IDC_EDIT_NAV_PIVOT              1122
#define IDC_EDIT_NAV_DELAY              1123
#define IDC_EDIT_NAV_MAX_TURN           1124
#define IDC_RADIO1                      1125
#define IDC_RADIO2                      1126
#define IDC_EDIT_NAV_D_LEN              1127
#define IDC_STATICPID_P4                1128
#define IDC_STATIC_NAV_TU               1129
#define IDC_EDIT_NAV_I_ACCUM            1129
#define IDC_BUTTON_CALC_PI              1130
#define IDC_BUTTON_CALC_PID2            1131
#define IDC_BUTTON_CALC_PI2             1132
#define IDC_BUTTON_CALC_ENABLE          1132
#define IDC_STATICPID_P5                1133
#define IDC_EDIT_NAV_TU                 1134
#define IDC_STATIC_NAV                  1135
#define IDC_SPIN_TU                     1136
#define IDC_STATIC_PID_RMS              1137
#define IDC_STATICPID_P6                1138
#define IDC_STATICPID_P7                1139
#define IDC_CHECK_SIMULATION            1140
#define IDC_EDIT_SIMULATION             1141
#define IDC_CHECK_FW_GAP                1141
#define IDC_STATIC_PID_RMS_P            1142
#define IDC_CHECK_FW_WELD               1142
#define IDC_STATIC_PROJECT              1142
#define IDC_STATIC_PID_RMS_I            1143
#define IDC_CHECK_FORCE_GAP             1143
#define IDC_STATIC_PID_RMS_D            1144
#define IDC_CHECK_FORCE_WELD            1144
#define IDC_BUTTON_CALC_PD              1145
#define IDC_BUTTON_CALC_NO_OVERSHOOT    1146
#define IDC_EDIT_NAV_PHZ                1147
#define IDC_SPIN_PHZ                    1148
#define IDC_BUTTON_SIMULATE             1149
#define IDC_EDIT_NAV_MAX_TURN_100       1150
#define IDC_EDIT_NAV_MAX_TURN_LEN       1151
#define IDC_STATICPID_P8                1152
#define IDC_EDIT_NAV_START_SPEED        1153
#define IDC_EDIT_NAV_START_DIST         1154
#define IDC_EDIT_NAV_GAP_PREDICT        1155
#define IDC_EDIT_NAV_P_LEN              1156
#define IDC_STATICPID_P9                1157
#define ID_POPUP_TOGGLELASER            32772
#define ID_POPUP_CENTREWELD             32773
#define ID_POPUP_PLAYOFFSETSOUND        32774
#define ID_FILE_OPEN32775               32775
#define ID_FILE_NEW32776                32776
#define ID_FILE_EXIT                    32777
#define ID_LASER_NAVIGATYEWELDCAP       32778
#define ID_LASER_NAVIGATEGAP            32779
#define ID_LASER_NAVIGATEWELDCAP        32780
#define ID_LASER_FORCE_GAP              32781
#define ID_LASER_FORCE_CAP              32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1143
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
