//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SimplyAUTMotionController.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SIMPLYAUT_MOTIONCONTROLLER_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_CONNECT              129
#define IDD_DIALOG_MOTORS               130
#define IDD_DIALOG_GIRTHWELD            131
#define IDB_BITMAP_DISCONNECT           132
#define IDD_DIALOG_STATUS               132
#define IDB_BITMAP_CONNECT              133
#define IDR_MENU_POPUP                  133
#define IDD_DIALOG_STATUS1              133
#define IDD_DIALOG_LASER                133
#define IDB_BITMAP_PAUSE                134
#define IDD_DIALOG_MAG                  134
#define IDB_BITMAP_GO_HORZ              135
#define IDB_BITMAP_GO_RIGHT             135
#define IDB_BITMAP_GO_VERT              136
#define IDB_BITMAP_GO_DOWN              136
#define IDB_BITMAP_STOP                 137
#define IDB_BITMAP_LASER_OK             138
#define IDB_BITMAP_LASER_LOADING        139
#define IDB_BITMAP_LASER_HOT            140
#define IDB_BITMAP_LASER_ERROR          141
#define IDB_BITMAP_LASER_OFF            142
#define IDB_BITMAP_GO_LEFT              143
#define IDB_BITMAP_GO_UP                144
#define IDC_BUTTON_CONNECT              1001
#define IDC_IPADDRESS_LASER             1004
#define IDC_IPADDRESS_GALIL             1005
#define IDC_BUTTON_LASER                1006
#define IDC_BUTTON_RGB                  1007
#define IDC_BUTTON_MAG                  1008
#define IDC_BUTTON_GALIL                1009
#define IDC_STATIC_LASER                1010
#define IDC_STATIC_RGB                  1011
#define IDC_STATIC_GALIL                1012
#define IDC_STATIC_LASER_IP             1013
#define IDC_IPADDRESS_MAG               1014
#define IDC_TAB1                        1015
#define IDC_STATIC_LASER_IP2            1015
#define IDC_EDIT_MA                     1016
#define IDC_STATIC_LASER_IP3            1016
#define IDC_EDIT_MB                     1017
#define IDC_EDIT_MC                     1018
#define IDC_EDIT_MD                     1019
#define IDC_STATIC_MA                   1020
#define IDC_STATIC_MB                   1021
#define IDC_STATIC_MC                   1022
#define IDC_STATIC_MD                   1023
#define IDC_STATIC_SPEED                1024
#define IDC_STATIC_LR_OFFSET            1025
#define IDC_EDIT_SPEED                  1026
#define IDC_SPIN_SPEED                  1027
#define IDC_EDIT_LR_OFFSET              1028
#define IDC_STATIC_SPEED2               1028
#define IDC_SPIN_LR_OFFSET              1029
#define IDC_EDIT_ACCEL                  1029
#define IDC_BUTTON_PAUSE                1030
#define IDC_SPIN_ACCEL                  1030
#define IDC_BUTTON_CALIB                1031
#define IDC_BUTTON_MANUAL               1032
#define IDC_BUTTON_AUTO                 1033
#define IDC_BUTTON_BACK                 1034
#define IDC_BUTTON_FWD                  1035
#define IDC_BUTTON_RIGHT                1036
#define IDC_EDIT_CIRC                   1037
#define IDC_SPIN_CIRC                   1038
#define IDC_BUTTON_ZERO_HOME            1039
#define IDC_BUTTON_GO_HOME              1040
#define IDC_STATIC_PAUSE                1041
#define IDC_EDIT_STATUS                 1042
#define IDC_EDIT_DIST                   1042
#define IDC_RADIO_CIRC                  1043
#define IDC_RADIO_DIST                  1044
#define IDC_SPIN_DIST                   1045
#define IDC_CHECK_AUTOHOME              1046
#define IDC_EDIT_OVERLAP                1047
#define IDC_STATIC_HOMEDIST             1048
#define IDC_SPIN_OVERLAP                1049
#define IDC_STATIC_SCANNEDDIST          1050
#define IDC_CHECK_RETURNTOSTART         1051
#define IDC_STATIC_JOINT_LOCN           1052
#define IDC_STATIC_LASER_US             1053
#define IDC_STATIC_LASER_DS             1054
#define IDC_STATIC_LASER_DIFF           1055
#define IDC_BUTTON_LASER_STATUS         1056
#define IDC_STATIC_MOTOR_A              1057
#define IDC_BUTTON_LEFT                 1057
#define IDC_STATIC_MOTOR_B              1058
#define IDC_CHECK_AUTO_REVERSE          1058
#define IDC_STATIC_MOTOR_C              1059
#define IDC_STATIC_TEMP_BOARD           1059
#define IDC_STATIC_MOTOR_A4             1060
#define IDC_STATIC_MOTOR_D              1060
#define IDC_STATIC_TEMP_LASER           1060
#define IDC_CHECK_MAG_ENGAGED           1061
#define IDC_STATIC_TEMP_SENSOR          1061
#define IDC_INITIALISE_BUTTON           1062
#define IDC_SERIALNUMBER_EDIT           1063
#define IDC_LASER_BUTTON                1064
#define IDC_TEMPERATURE_EDIT            1065
#define IDC_MSG_EDIT                    1066
#define IDC_LASERPOWER_BUTTON           1067
#define IDC_LASERPOWER_EDIT             1068
#define IDC_SENSORVERSION_EDIT          1069
#define IDC_CALIBRATIONVERSION_EDIT     1070
#define IDC_AUTOLASER_CHECK             1071
#define IDC_PROFILECOUNT_EDIT           1072
#define IDC_LASERPOWER_SLIDER           1073
#define IDC_SHUTTER_SLIDER              1074
#define IDC_SHUTTER_EDIT                1075
#define IDC_JOINTPOS_EDIT               1076
#define IDC_EDGESPOS_EDIT               1077
#define IDC_GAPVALUE_EDIT               1078
#define IDC_MISMATCHVALUE_EDIT          1079
#define IDC_ROI_BUTTON                  1080
#define IDC_ROI_EDIT                    1081
#define IDC_CLOSE_BUTTON                1082
#define IDC_STATIC_PROFILE              1083
#define IDC_EDIT_MAG_PORT               1084
#define IDC_STATIC_MAG_VERSION          1085
#define IDC_STATIC_MAG_ENCODER          1086
#define IDC_CHECK_MAG_ENABLE            1087
#define IDC_BUTTON_MAG_CLEAR            1088
#define IDC_STATIC_MAG_ENCODER2         1089
#define IDC_STATIC_MAG_RGB              1089
#define IDC_BUTTON_MAG_ON               1090
#define ID_POPUP_SETLOCATION            32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
